auth_enabled: false #-> без авторизации

server:
  http_listen_post: 3100 #-> loki слушает запросы на порту 3100

ingester: #-> приемщик логов
  lifecycler: #-> Управление жизненным циклом и хранением чанков(частей логов).
    address: 0.0.0.0
    ring:
      kvstore:
        store: summary
      replication_factor: 1 #-> без репликации
    final_sleep: 0s
  chunk_idle_period: 5m #-> Тайминги
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:  #-> Логи(чанки) в файловой системе
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

limits_config: #-> Ограничения по приему логов: до 8mb/s
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h #-> Отбрасываются слишком старые записи
  ingestion_rate_mb: 8
  ingestion_burst_size_md: 10 #-> burst

chunk_storage_config: #-> Без ограничения по времени на поиск в чанках.
  max_look_back_period: 0s

table_manager: #-> Управляет таблицами логов и чанков.
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true #-> Автоматические удаления включены
  retention_period: 672h #-> хранение логов ~28 дней